id: timelapse
name: Timelapse
name[zh]: 延时摄影
version: 1.0.3
icon: icon.png
author: Sipeed Ltd
desc: Record a time-lapse video
desc[zh]: 录制延时视频
files:
  - icon.png
  - app.yaml
  - assets
  - README.md
