id: self_learn_classifier
name: Self Learn Classifier
name[zh]: 自学习分类
version: 1.0.4
author: Sipeed Ltd
icon: app.png
desc: Learn anything on device, no PC training needed.
files:
  - app.png
  - app.yaml
  - main.py
